# Generated by Django 4.2.7 on 2024-02-11 01:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('rate', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('date', models.DateField(default=datetime.datetime(2024, 2, 11, 1, 48, 12, 141988, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('stack', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=10)),
                ('downloads', models.IntegerField()),
                ('fileName', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Products',
            },
        ),
    ]
