# Generated by Django 5.0.4 on 2024-06-17 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_like_visit_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 6, 17, 4, 42, 42, 135715, tzinfo=datetime.timezone.utc)),
        ),
    ]
