# Generated by Django 5.0.3 on 2024-04-06 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_buttonclick_like_alter_comments_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 6, 10, 22, 1, 156422, tzinfo=datetime.timezone.utc)),
        ),
    ]
